### ISSUE TITLE
File write in `vendor/` breaks notification pushes

### ISSUE THREAD

**Issue by alexisLefebvre** [Alymosul/exponent-server-sdk-php#30]
It looks like the library try to create a file in the `vendor/` directory: #6

This breaks our app because we built a Docker image and the `vendor/` directory is not writable.

I think that it's not a good idea to write a temporary file in `vendor/`.

Can we configure another path?

We may use [`sys_get_temp_dir()`](http://php.net/manual/en/function.sys-get-temp-dir.php) in order to get a writable path.

**Comment by talvbansal** [comment]
I've had the same issue on an ubuntu server. I had to create the tokens.json file then make it writeable by my webserver. 

Not ideal by any means as it adds a new build step that needs to be remembered to created.

@alexislefebvre in the mean time you could make a local copy of ExpoFileDriver class and update its `$storage` property then instead of calling `Expo::normalSetup()` new up an instance using your local class `new Expo(new ExpoRegistrar(new LocalExpoFileDriver)));`

**Comment by talvbansal** [comment]
Looks like this is fixed in the latest update. 

@Alymosul this can be closed :)

**Comment by alexisLefebvre** [comment]
Thanks for the news, it should have been fixed in #33.
