### ISSUE TITLE
Notify with expo token directly

### ISSUE THREAD

**Issue by ariselseng** [Alymosul/exponent-server-sdk-php#5]
First I would like to say this is a very nice project.
For my use case, I would really like to send a notification without subscribing a user.
I already have the expo token stored.
Is this something worth having in your project?

**Comment by Alymosul** [comment]
I think i will stick with the existing approach to subscribe(store) the token first, I can't see why shouldn't we subscribe the user.

**Comment by kimchirichie** [comment]
id like to reopen this case and put the spotlight on current approach of storing tokens.

currently all user token relationship is **stored in a local json file** `tokens.json`. this is problematic for heroku instances (dynos) as they are cleaned out when switching dynos.

It would be great to send notifications without subscribing a user.

**Comment by eddietex** [comment]
I agree with @kimchirichie . We also have all tokens stored in a database, and for our application, we have different groups of "subscribers", and we rely on the information on the DB to pick who should receive the notifications. It would be extra work to have all that logic on the database and also need to keep up with the tokens.json file logic.

**Comment by nnals** [comment]
@Alymosul just like @esdrasevt we have everything stored in the database hence the token management as it's done by this library is not very useful for us. do you think it makes sense to adapt this library so that it's possible to just use the notify function or would that diverge too much from your goals? i could either try to make a PR or write a second library. 
take care

**Comment by Alymosul** [comment]
I'm open to any PR that would add an additional database driver or would allow to send notifications on the fly but please provide tests with it, it makes it easier for me to merge it :)

**Comment by dagan-arbox** [comment]
anything about this issue? I can only get this to work after:
sudo chown -R www-data:www-data /var/www/html/app/current/vendor/alymosul/exponent-server-sdk-php/storage/

this is on staging env, on prod it's a big issue for me

**Comment by Alymosul** [comment]
You can customize the storage path through calling `setStorage()` on the `ExpoFileDriver`

```
$fileDriver = (new ExpoFileDriver)->setStorage('your path');

// Then instantiate ExpoRegistrar with that fileDriver you just created.
new Expo(new ExpoRegistrar($fileDriver));
```

**Comment by dagan-arbox** [comment]
can you recommend a place to put it, right now the only place I use it, is when sending, I guess to set path each time is not needed.
one more thing. it fails on "Creating default object from empty value"
I guess because jsons does not exists there
can it be created automatically, it is an issue because using ec2 instances, harder to handle when not done automatically
